packets = [
    '(01) Alabama: Yellowhammer bird',
    '(02) Alaska: Willow Ptarmigan',
    '(03) Arizona: Cactus Wren',
    '(04) Arkansas: Northern Mockingbird',
    '(05) California: California Valley Quail',
    '(06) Colorado: Lark Bunting',
    '(07) Connecticut: American Robin',
    '(08) Delaware: Blue Hen Chicken',
    '(09) Florida: Mockingbird',
    '(10) Georgia:Brown Thrasher',
    '(11) Hawaii: Nene',
    '(12) Idaho: Mountain Bluebird',
    '(13) Illinois: Cardinal',
    '(14) Indiana: Cardinal',
    '(15) Iowa: Eastern Goldfinch',
    '(16) Kansas: Western Meadowlark',
    '(17) Kentucky: Cardinal',
    '(18) Louisiana: Eastern Brown Pelican',
    '(19) Maine: Chickadee',
    '(20) Maryland: Baltimore Oriole',
    '(21) Massachusetts:Chickadee',
    '(22) Michigan: Robin',
    '(23) Minnesota: Common Loon',
    '(24) Mississippi: Mockingbird',
    '(25) Missouri: Bluebird',
    '(26) Montana: Western Meadowlark',
    '(27) Nebraska: Western Meadowlark',
    '(28) Nevada: Mountain Bluebird',
    '(29) New Hampshire: Purple Finch',
    '(30) New Jersey: Eastern Goldfinch',
    '(31) New Mexico: Roadrunner',
    '(32) New York: Eastern Bluebird',
    '(33) North Carolina: Cardinal',
    '(34) North Dakota: Western Meadowlark',
    '(35) Ohio: Cardinal',
    '(36) Oklahoma: Scissor-tailed Flycatcher',
    '(37) Oregon: Western Meadowlark',
    '(38) Pennsylvania: Ruffed Grouse',
    '(39) Rhode Island: Rhode Island Red Hen',
    '(40) South Carolina: Carolina Wren',
    '(41) South Dakota: Ring-necked Pheasant',
    '(42) Tennessee: Mockingbird',
    '(43) Texas: Mockingbird',
    '(44) Utah: Ring-billed Gull',
    '(45) Vermont: Hermit Thrush',
    '(46) Virginia: Cardinal',
    '(47) Washington: Willow Goldfinch',
    '(48) West Virginia: Cardinal',
    '(49) Wisconsin: Robin',
    '(50) Wyoming: Western Meadowlark',
]
